theme: jekyll-theme-cayman
title: Mapa wycieczek
description: Mapa prezentująca kraje przeze mnie odwiedzone oraz obserwacje poczynione podczas pobytu.
google_analytics: https://www.googletagmanager.com/gtag/js?id=UA-138292571-2
